name: MordSheets
version: '${project.version}'
main: me.billbominecraft.mordsheets.MordSheets
api-version: 1.19
authors: [ billbominecraft ]
description: Minecraft character sheets

commands:
  roll:
    description: Roll a random number from 1 to 20
    usage: /roll [#]

  groll:
    description: Globally roll a random number 1 to 20
    usage: /groll [#]

  cs:
    description: View/edit character sheets
    usage: /cs

  rs:
    description: View/edit roleplay stats
    usage: /rs